---
webdriver_path: 'C:/chromedriver'
url: "https://shopee.sg/Slippers-Women-Soft-Home-Slipper-Indoor-Slipper-Anti-Skid-Bathroom-Slippers-Men-Super-Light-i.426844879.8590715201?sp_atk=e590af8b-b36f-4293-8a30-a40f89dbb103"